PersonalFinanceTracker/Controllers/BanksController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using PersonalFinanceTracker.Model;
using PersonalFinanceTracker.Service;
using PersonalFinanceTracker.SQL;
using PersonalFinanceTracker.SQL.Models;

namespace PersonalFinanceTracker.Controllers
{
    [Authorize]
    public class BankController : BaseController
    {
        private readonly ILogger<BankController> _logger;
        private Microsoft.AspNetCore.Hosting.IHostingEnvironment _environment;
        private readonly IConfiguration configuration;
        private readonly PFTDbContext _dbContext;
        private readonly BanksService _banksService;
        private readonly UsersService _usersService;
        private readonly PlainLinkService _plainLinkService;

        public BankController(ILogger<BankController> logger,
            PFTDbContext dbContext,
            UsersService usersService,
            BanksService banksService,
            PlainLinkService plainLinkService,
            Microsoft.AspNetCore.Hosting.IHostingEnvironment environment, IConfiguration configuration)
        {
            _logger = logger;
            _plainLinkService = plainLinkService;
            _banksService = banksService;
            _usersService = usersService;
            _dbContext = dbContext;
            _environment = environment;
            this.configuration=configuration;
        }

        public IActionResult Index(Guid? userId, Query query)
        {
            return View();
        }

        public async Task<PagedEntities<Banks>> GetBanks(Guid? userId, Query query)
        {
            if (!userId.HasValue)
                userId = GetUserId(_dbContext);

            return await _banksService.GetBanks(userId.Value, query);
        }

        public async Task<ActionResult> Add()
        {
            var banksOut = new BanksOut();
            var userId = GetUserId(_dbContext);

            banksOut.UserCurrencyCode = await _usersService.GetUserCurrencyCodes(userId);
            return View(banksOut);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Add(BanksIn bank)
        {
            if (!ModelState.IsValid)
            {
                ModelStateException(ModelState);
            }

            var userId = GetUserId(_dbContext);

            await _banksService.AddBanks(userId, bank);
            return RedirectToAction("Index");
        }

        public async Task<ActionResult> Edit(Guid? id)
        {
            if (!id.HasValue)
                throw new Exception("Bank Id not given");

            var bank = await _banksService.Get(id.Value);
            var userId = GetUserId(_dbContext);

            var banksOut = Banks.GetBankOut(bank);
            banksOut.UserCurrencyCode = await _usersService.GetUserCurrencyCodes(userId);
            banksOut.UpdatedDateTime = DateTime.Now;
            return View(banksOut);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(BanksOut banks)
        {
            if (!ModelState.IsValid)
            {
                ModelStateException(ModelState);
            }

            var bank = Banks.GetBank(banks);
            _banksService.Edit(bank);
            return RedirectToAction("Index");
        }

        public async Task<ActionResult> Delete(Guid? id)
        {
            if (!id.HasValue)
                throw new Exception("Id is null");

            var bank = await _banksService.Get(id.Value);
            return View(bank);
        }
        
        public async Task<JsonResult> CreateLinkToken([FromQuery] bool? fix)
        {
            var token = await _plainLinkService.CreateLinkToken(fix);
            return new JsonResult(token);
        }

        [HttpPost]
        public async Task<PlaidCredentials> ExchangeToken([FromBody] LinkResult link)
        {
            var userId = GetUserId(_dbContext);
            var result = await _plainLinkService.ExchangePublicToken(link.public_token, userId);
            return result;
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteBank(Guid id)
        {
            if (id == Guid.Empty)
            {
                throw new Exception("Invalid Input");
            }

            _banksService.Delete(id);
            return RedirectToAction("Index");
        }
    }
}

PersonalFinanceTracker/Controllers/ExpenseController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using PersonalFinanceTracker.Model;
using PersonalFinanceTracker.Service;
using PersonalFinanceTracker.SQL;
using PersonalFinanceTracker.SQL.Models;

namespace PersonalFinanceTracker.Controllers
{
    public class ExpenseController : BaseController
    {
        private readonly ILogger<ExpenseController> _logger;
        private readonly IConfiguration configuration;
        private readonly PFTDbContext _dbContext;
        private readonly BanksService _banksService;
        private readonly ExpenseService _expenseService;
        private readonly UsersService _usersService;
        private readonly IMapper _mapper;

        public ExpenseController(ILogger<ExpenseController> logger,
            BanksService banksService,
            PFTDbContext dbContext,
            IMapper mapper,
            IConfiguration configuration,
            ExpenseService expenseService,
            UsersService usersService)
        {
            _logger = logger;
            _banksService = banksService;
            _dbContext = dbContext;
            this.configuration=configuration;
            _expenseService=expenseService;
            _usersService=usersService;
            _mapper=mapper;
        }

        public IActionResult Index()
        {
            return View();
        }

        public async Task<PagedEntities<Expenses>> GetExpense(Guid? userId, DateTime? startDate, DateTime? endDate, Query query)
        {
            if (!userId.HasValue)
                userId = GetUserId(_dbContext);

            return await _expenseService.GetExpenses(userId.Value, startDate, endDate, query);
        }

        public async Task<ActionResult> Create()
        {
            var userId = GetUserId(_dbContext);
            var userBanks = await _banksService.GetUserBanks(userId);
            var userCurrencies = await _usersService.GetUserCurrencyCodes(userId);
            return View(new AddExpenseDetail
            {
                UserCurrencies = userCurrencies,
                UserId = userId,
                Banks = userBanks,
                Date = DateTime.Today
            });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(ExpenseIn expense)
        {
            if (!ModelState.IsValid)
            {
                ModelStateException(ModelState);
            }

            await _expenseService.AddExpense(expense);
            return RedirectToAction("Index");
        }

        public async Task<ActionResult> Edit(Guid? id)
        {
            var expense = await _expenseService.Get(id);
            var expenseOut = _mapper.Map<ExpenseOut>(expense);
            expenseOut.Amount = expense.Amount;

            expenseOut.UpdatedDateTime = DateTime.UtcNow;
            var userId = GetUserId(_dbContext);

            var userBanks = await _banksService.GetUserBanks(userId);

            var userCurrencies = await _usersService.GetUserCurrencyCodes(userId);

            expenseOut.UserCurrencies = userCurrencies;
            expenseOut.Banks = userBanks;
            return View(expenseOut);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> EditExpense(ExpenseIn expenseOut)
        {
            if (!ModelState.IsValid)
            {
                ModelStateException(ModelState);
            }

            var userId = GetUserId(_dbContext);
            var expenses = _mapper.Map<Expenses>(expenseOut);
            expenses.EncryptedAmount = expenseOut.Amount.ToString();

            await _expenseService.Edit(expenses, userId);
            return RedirectToAction("Index");
        }

        public async Task<ActionResult> Delete(Guid? id)
        {
            var expense = await _expenseService.Get(id);
            return View(expense);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Delete(Guid id)
        {
            if (id == Guid.Empty)
            {
                throw new Exception("Invalid Input");
            }

            var userId = GetUserId(_dbContext);
            await _expenseService.Delete(id, userId);
            return RedirectToAction("Index");
        }
    }
}

PersonalFinanceTracker/Controllers/IncomeController.cs
using System.Diagnostics;
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration.UserSecrets;
using PersonalFinanceTracker.Model;
using PersonalFinanceTracker.Model.Helpers;
using PersonalFinanceTracker.Models;
using PersonalFinanceTracker.Service;
using PersonalFinanceTracker.SQL;
using PersonalFinanceTracker.SQL.Models;
using static Microsoft.EntityFrameworkCore.DbLoggerCategory;

namespace PersonalFinanceTracker.Controllers
{
    public class IncomeController : BaseController
    {
        private readonly PFTDbContext _dbContext;
        private readonly IncomeService _incomeService;
        private readonly BanksService _banksService;
        private readonly IMapper _mapper;
        private readonly UsersService _usersService;

        public IncomeController(PFTDbContext dbContext, IncomeService incomeService,
            IMapper mapper,
            UsersService usersService,
             BanksService banksService)
        {
            _dbContext = dbContext;
            _incomeService = incomeService;
            _banksService = banksService;
            _mapper = mapper;
            _usersService = usersService;
        }

        public async Task<IActionResult> Index()
        {
            var dateTime = DateHelper.GetDefaultStartEndTimeOfMonth();
            var userId = GetUserId(_dbContext);
            var incomes = GetIncome(userId, dateTime.Item1, dateTime.Item2, null);
            return View(incomes);
        }

        public async Task<PagedEntities<Income>> GetIncome(Guid? userId, DateTime? startDate, DateTime? endDate, PersonalFinanceTracker.Model.Query query)
        {
            if (!userId.HasValue)
                userId = GetUserId(_dbContext);

            ValidateUser(userId.Value);
            return await _incomeService.GetIncomes(userId.Value, startDate, endDate, query);
        }

        public async Task<ActionResult> Add()
        {
            var userId = GetUserId(_dbContext);
            var userBanks = await _banksService.GetUserBanks(userId);

            return View(new AddIncomeDetail
            {
                UserCurrencies = await _usersService.GetUserCurrencyCodes(userId),
                Banks = userBanks,
                IncomeDate = DateTime.Today
            });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Add(IncomeIn incomeIn)
        {
            if (!ModelState.IsValid)
            {
                ModelStateException(ModelState);
            }

            var userId = GetUserId(_dbContext);
            incomeIn.UserId = userId;
            await _incomeService.AddIncome(incomeIn);
            return RedirectToAction("Index");
        }

        public async Task<ActionResult> Edit(Guid? id)
        {
            var income = await _incomeService.Get(id);
            var incomeOut = _mapper.Map<IncomeOut>(income);
            incomeOut.Amount = income.Amount;
            incomeOut.UpdatedDateTime = DateTime.Now;

            var userId = GetUserId(_dbContext);
            var userBanks = await _banksService.GetUserBanks(userId);
            incomeOut.Banks = userBanks;

            incomeOut.UserCurrencies = await _usersService.GetUserCurrencyCodes(userId);

            return View(incomeOut);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> EditIncome(IncomeIn incomeOut)
        {
            if (!ModelState.IsValid)
            {
                ModelStateException(ModelState);
            }

            var income = _mapper.Map<Income>(incomeOut);
            income.EncryptedAmount = incomeOut.Amount.ToString();
            await _incomeService.Edit(income);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult DownloadExcel()
        {
            // Define the path to the file
            var filePath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "StatementSamplev1.xlsx");
            byte[] fileBytes = System.IO.File.ReadAllBytes(filePath);
            string fileName = "StatementSamplev1.xlsx";
            return File(fileBytes, System.Net.Mime.MediaTypeNames.Application.Octet, fileName);
        }

        public async Task<ActionResult> Delete(Guid? id)
        {
            var income = await _incomeService.Get(id);
            return View(income);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Delete(Guid id)
        {
            if (id == Guid.Empty)
            {
                throw new Exception("Invalid Input");
            }

            await _incomeService.Delete(id);
            return RedirectToAction("Index");
        }

        public async Task<ActionResult> Details(Guid? id)
        {
            var income = await _incomeService.Get(id);
            return View(income);
        }

        private void ValidateUser(Guid userId)
        {
            if (userId == Guid.Empty)
                throw new Exception("Invalid User");

            var isUserExists = _dbContext.Users.Any(u => u.Id == userId);
            if (!isUserExists)
                throw new Exception("User not found");
        }
    }
}

PersonalFinanceTracker/Controllers/ToolsController.cs
using Microsoft.AspNetCore.Mvc;

namespace PersonalFinanceTracker.Controllers
{
    public class ToolsController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult RetirementCalculator()
        {
            return View();
        }

        public IActionResult LoanCalculator()
        {
            return View();
        }
    }
}

PersonalFinanceTracker/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PersonalFinanceTracker</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/PersonalFinanceTracker.styles.css" asp-append-version="true" />

    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.4/Chart.js"></script>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/js/moment.min.js"></script>

    @* DateRange Picker *@
    <link rel="stylesheet" href="~/css/daterangepicker.3.14.1.css" />
    <script src="~/js/daterangepicker.3.14.1.min.js" defer></script>

    <script>
        var global = {
        };

        // Make user-specific data available globally in JavaScript
        window.userCurrencies = "@ViewData["UserCurrencies"]";
        console.log("User Currency: ", window.userCurrencies);
    </script>

    <script src="~/js/app/helper.js" defer></script>
    <script src="~/js/app/controller.js" defer></script>
    @* DataTable *@
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.11.5/css/jquery.dataTables.min.css">
    <script type="text/javascript" src="https://cdn.datatables.net/1.11.5/js/jquery.dataTables.min.js"></script>

    @* Font Awesome *@
    <script src="https://kit.fontawesome.com/421c46371b.js" crossorigin="anonymous"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Personal Finance Tracker</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    @if (User.Identity?.IsAuthenticated == true)
                    {

                        <ul class="navbar-nav flex-grow-1 align-center">
                            @*  <li class="nav-item">
                        <a class="nav-link text-dark @Html.ActiveClass("/Home/Index")" asp-area="" asp-controller="Home" asp-action="Index">Overview</a>
                        </li> *@
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Income" asp-action="Index">Income</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Expense" asp-action="Index">Expense</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Bank" asp-action="Index">Bank</a>
                            </li>
                            <li class="nav-item dropdown pt-2">
                                <a class="nav-link dropdown-toggle text-dark" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    Tools
                                </a>
                                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <li>
                                        <a class="dropdown-item" asp-area="" asp-controller="FireCalculator" asp-action="Index">FIRE Calculator</a>
                                    </li>
                                    <li>
                                        <a class="dropdown-item" asp-area="" asp-controller="Tools" asp-action="RetirementCalculator">Retirement Calculator</a>
                                    </li>
                                    <li>
                                        <a class="dropdown-item" asp-area="" asp-controller="Tools" asp-action="LoanCalculator">Loan Calculator</a>
                                    </li>
                                    <!-- You can add more dropdown items here -->
                                </ul>
                            </li>
                            <li class="dropdown pull-right" style="padding-left:50px;">
                                <input class="styled-select" type="text" title="daterangepicker" id="dateRangePicker">
                            </li>

                        </ul>
                    }
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container-fluid">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container-fluid">
            &copy; @DateTime.UtcNow.Year - PersonalFinanceTracker - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>